inherit_gem:
  rubocop-rails:
    - config/rails.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - Rakefile
    - Gemfile
    - db/schema.rb
    - spec/rails_helper.rb
    - config/*
    - config/**/*
    - bin/*
    - config.ru
    - app/chanels/*
    - app/chanels/application_cable/*.rb
Style/FrozenStringLiteralComment:
  Enabled: false
